[buildPlans.iosevka]
family = "Iosevka"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevka.variants]
  inherits = "ss08"

    [buildPlans.iosevka.variants.design]
    capital-d = "standard-serifless"
    capital-g = "toothless-corner-serifless-hooked"
    capital-i = "short-serifed"
    capital-j = "serifed"
    capital-n = "standard-serifless"
    capital-q = "open-swash"
    capital-r = "straight-open-serifless"
    capital-v = "straight-serifless"
    capital-w = "straight-serifless"
    a = "double-storey-toothless-corner"
    g = "double-storey-open"
    l = "serifed-flat-tailed"
    m = "earless-corner-double-arch-serifless"
    n = "earless-corner-straight-serifless"
    p = "earless-corner-serifless"
    q = "earless-corner-straight-serifless"
    r = "earless-corner-serifless"
    t = "flat-hook-short-neck"
    u = "toothless-corner-serifless"
    v = "straight-serifless"
    y = "curly-turn-serifless"
    zero = "dotted"
    four = "open"
    six = "straight-bar"
    seven = "straight-serifless"
    nine = "straight-bar"
    paren = "flat-arc"
    number-sign = "upright"
    ampersand = "upper-open"
    percent = "rings-continuous-slash"

    [buildPlans.iosevka.variants.italic]
    e = "rounded"
    f = "tailed"
    k = "cursive-serifless"
    z = "cursive"
