name: Build font

on:
  push:
    tags:
      - '*'
    branches: [ "build" ]
#   pull_request:
#     branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Install ttfautohint
      run: sudo apt install ttfautohint
        
    # - uses: pnpm/action-setup@v3
    #   with:
    #     version: 8

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
        
    - name: Install npm dependencies
      run: npm install
    
    - name: Build fonts
      run: npm run build -- contents::iosevka

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: dist/
    
    - name: 'Create tagged artefact'
      uses: actions/upload-artifact@v4
      with:
        name: font-artefact_${{github.ref_name}}
        path: dist/
    
